modLoader="kotlinforforge"
loaderVersion="${loader_version_range}"
license='${mod_license}'

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="Thanks to the Kotlin For Forge team and Neoforge team!"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile = "logo.png"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side = "CLIENT"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side = "CLIENT"
